name: Mystery V2
author: "@Ichinichi"
description: | 
  Постирония развивается не по дням, а по часам. Помогите товарищу майору справиться с новым вызовом мемоделов
category: stegano
value: 100
type: dynamic

extra:
    initial: 100
    decay: 10
    minimum: 10

flags:
  - vrnctf{r6b_t0_7z_4rch1v3}

files:
  - public/image.png

state: visible
version: "0.1"