name: Ruins
author: "@jim_amlt"
description: |
  Мы нашли странную дверь, когда исследовали руины, но она не открывается...
  Может быть, мы сможем как-то посмотреть на внутреннее устройство двери?
#сюда бы пикчу... https://codigoespagueti.com/wp-content/uploads/2022/11/suzume-no-tojimari-nuevo-trailer.jpg
category: reverse
value: 100
type: dynamic

extra:
    initial: 100
    decay: 10
    minimum: 10

flags:
  - vrnctf{7r345ur3_15_y0u_4nd_y0ur_fr13nd5}

state: visible
version: "0.1"