# –û–±—è–∑–∞—Ç–µ–ª—å–Ω—ã–µ –ø–æ–ª—è
# –ò–º—è –∑–∞–¥–∞—á–∏ –Ω–∞ CTFd
name: Encryptor
# –ù–∏–∫–Ω–µ–π–º –≤ Telegram
author: "@alexereh"
# –û–ø–∏—Å–∞–Ω–∏–µ —Ç–∞—Å–∫–∞ –Ω–∞ –ø–ª–∞—Ç—Ñ–æ—Ä–º–µ.
description: | 
  –ë—ã–ª–∞ –æ–±–Ω–∞—Ä—É–∂–µ–Ω–∞ –ø—Ä–æ–≥—Ä–∞–º–º–∞, –∫–æ—Ç–æ—Ä–∞—è –¥–µ–ª–∞–µ—Ç –∏–∑ –±—É–∫–æ–≤–æ–∫... —Ü–∏—Ñ–µ—Ä–∫–∏... ü§î
# –û–¥–Ω–∞ –∏–∑ —Å–ª–µ–¥—É—é—â–∏—Ö –∫–∞—Ç–µ–≥–æ—Ä–∏–π: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: crypto
# –û—Å—Ç–∞–≤–ª—è–µ–º –∫–∞–∫ –µ—Å—Ç—å - —Ü–µ–Ω–∞ —Ç–∞—Å–∫–∏
value: 100
# –ù–µ —Ç—Ä–æ–≥–∞–µ–º - —Ç–∏–ø —Å–æ—Ä–µ–≤–Ω–æ–≤–∞–Ω–∏—è
type: dynamic

extra:
    # –°—Ç–∞—Ä—Ç–æ–≤–∞—è —Ü–µ–Ω–∞
    initial: 100
    # –°–∫–æ–ª—å–∫–æ –∫–æ–º–∞–Ω–¥ –¥–æ–ª–∂–Ω—ã —Ä–µ—à–∏—Ç—å, —á—Ç–æ–±—ã —Ü–µ–Ω–∞ —É–ø–∞–ª–∞ –¥–æ –º–∏–Ω–∏–º—É–º–∞
    decay: 10
    # –ú–∏–Ω–∏–º–∞–ª—å–Ω–∞—è —Ü–µ–Ω–∞
    minimum: 10

# –§–ª–∞–≥.
flags:
  - vrnctf{w0w_pr1m3s}

# –î–ª—è –∞–¥–º–∏–Ω–æ–≤
# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# –î–ª—è —É—á–∞—Å—Ç–Ω–∏–∫–æ–≤
# tags:
#   - web
#   - sandbox
#   - js

# –°–µ–∫—Ü–∏—è —Å —Ñ–∞–π–ª–∏–∫–∞–º–∏, –∫–æ—Ç–æ—Ä—ã–µ –æ—Ç–¥–∞—é—Ç—Å—è —É—á–∞—Å—Ç–Ω–∏–∫–∞–º–∏. –û—Ç–Ω–æ—Å–∏—Ç–µ–ª—å–Ω—ã–π –ø—É—Ç—å –æ—Ç –ø–∞–ø–∫–∏ public
files:
  - public/encrypt.txt
  - public/encrypt.py

# –û—Ç–æ–±—Ä–∞–∂–µ–Ω–∏–µ –Ω–∞ –ø–ª–∞—Ç—Ñ–æ—Ä–º–µ. visible/hidden
state: visible
version: "0.1"